\set ON_ERROR_STOP on
begin;
\ir _helpers.sql
\ir fixtures/confirmation_flow_fixture.sql

select extensions.gen_random_uuid() as test_run_id \gset
select support_vnext_test.create_complaint_proposal_fixture(:'test_run_id'::uuid,'{"relato":"teste P10"}'::jsonb);
select release_id,session_id,topic_id from support_vnext_test.complaint_proposal_fixture_context where test_run_id=:'test_run_id'::uuid \gset
-- P10-SQL: the real resolver sees no published applicable rule. The decision
-- engine (tested in Deno) turns this empty set into A_CONFIRMAR.
select support_vnext_shadow.get_runtime_decision_rules(:'release_id'::uuid,'UNMATCHED_INTENT','UNMATCHED_SERVICE',null) as runtime_rules \gset
select pg_temp.assert_true(:'runtime_rules'::jsonb='[]'::jsonb,'P10 SQL resolver returns empty applicable rule set');
select count(*) as decision_rule_count from support_vnext_shadow.decision_rule where release_id=:'release_id'::uuid \gset
select pg_temp.assert_true(:decision_rule_count::integer=0,'P10 fixture has no matching persisted decision_rule for the resolver boundary');
select pg_temp.assert_true((select count(*)=0 from support_vnext_shadow.service_requests where session_id=:'session_id'::uuid),'P10 SQL phase creates no request');
select pg_temp.assert_true((select count(*)=0 from support_vnext_shadow.service_requests where session_id=:'session_id'::uuid and protocol is not null),'P10 SQL phase creates no protocol');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions','[]'::jsonb,'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations','[]'::jsonb),'validation_requirements','{}'::jsonb,'response_plan',jsonb_build_object('mode','DETERMINISTIC','template_variables',jsonb_build_object('price',10),'allowed_fact_refs','[]'::jsonb,'asset_ids','[]'::jsonb,'max_questions',0),'request_plan',null,'document_plan',null,'handoff_plan',null)),'P10-A price hidden in template_variables rejected');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions','[]'::jsonb,'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations','[]'::jsonb),'validation_requirements','{}'::jsonb,'response_plan',null,'request_plan',jsonb_build_object('mode','PROPOSE','request_policy_id',gen_random_uuid(),'subject_template_id',gen_random_uuid(),'proposal_field_values',jsonb_build_object('documents','x'),'document_ids','[]'::jsonb,'confirmation_required',true),'document_plan',null,'handoff_plan',null)),'P10-B documents and P10-G automatic request rejected');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions','[]'::jsonb,'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations',jsonb_build_array(jsonb_build_object('op','MERGE_COLLECTED_DATA','topic_id',:'topic_id'::text,'allowed_fields',jsonb_build_object('deadline','x')))),'validation_requirements','{}'::jsonb,'response_plan',null,'request_plan',null,'document_plan',null,'handoff_plan',null)),'P10-C prazo, P10-D SLA and P10-E administrative condition rejected');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions',jsonb_build_array('CRIAR_SOLICITACAO'),'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations','[]'::jsonb),'validation_requirements','{}'::jsonb,'response_plan',null,'request_plan',null,'document_plan',null,'handoff_plan',null)),'P10-F final administrative decision rejected');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions','[]'::jsonb,'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations','[]'::jsonb),'validation_requirements',jsonb_build_object('legacy','service_price'),'response_plan',null,'request_plan',null,'document_plan',null,'handoff_plan',null)),'P10-H service_* and P10-I legacy fallback rejected');
select pg_temp.assert_true(not support_vnext_shadow.valid_decision_plan(jsonb_build_object('schema_version','1.0','release_id',:'release_id'::text,'outcome','A_CONFIRMAR','actions','[]'::jsonb,'reason_codes','[]'::jsonb,'state_patch',jsonb_build_object('expected_state_version',1,'operations','[]'::jsonb),'validation_requirements','{}'::jsonb,'response_plan',jsonb_build_object('mode','DETERMINISTIC','template_variables',jsonb_build_object('safe',jsonb_build_object('price',10)),'allowed_fact_refs','[]'::jsonb,'asset_ids','[]'::jsonb,'max_questions',0),'request_plan',null,'document_plan',null,'handoff_plan',null)),'P10-J nested factual renderer escape rejected');
\echo 'PASS P10-SQL resolver boundary and P10-A..P10-J structural fail-closed checks; renderer/proposal chain is covered by the prepared Deno integration test'
rollback;
