-- C4-R5C: closed, typed DecisionPlan and DecisionRule JSON contracts.
begin;

create or replace function support_vnext_shadow.is_uuid_text(p text) returns boolean language plpgsql immutable strict set search_path=pg_catalog as $$ begin perform p::uuid; return true; exception when invalid_text_representation then return false; end $$;
create or replace function support_vnext_shadow.is_timestamptz_text(p text) returns boolean language plpgsql immutable strict set search_path=pg_catalog as $$ begin perform p::timestamptz; return true; exception when invalid_datetime_format then return false; end $$;
create or replace function support_vnext_shadow.valid_scalar_value(p jsonb) returns boolean language sql immutable as $$ select jsonb_typeof(p) in ('string','number','boolean','null') $$;
create or replace function support_vnext_shadow.valid_template_variables(p jsonb) returns boolean language sql immutable as $$
 select jsonb_typeof(p)='object' and not exists(select 1 from jsonb_each(p) x where x.key !~ '^[a-z][a-z0-9_]{0,63}$' or x.key in ('severity','gravidade','priority','sector','setor','assigned_sector','external_route','ouvidoria','email','automatic_email','admin_decision') or jsonb_typeof(x.value) not in ('string','number','boolean')) $$;
create or replace function support_vnext_shadow.valid_fact_refs(p jsonb) returns boolean language sql immutable as $$
 select jsonb_typeof(p)='array' and not exists(select 1 from jsonb_array_elements(p) x where not support_vnext_shadow.closed_object(x,array['type','id']) or x->>'type' not in ('PRICE','DOCUMENT','HOURS','CONDITION','MESSAGE','ASSET') or not support_vnext_shadow.is_uuid_text(x->>'id')) $$;
create or replace function support_vnext_shadow.valid_question_schema(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['question_code','expected_answer_schema']) and p->>'question_code' ~ '^[A-Z][A-Z0-9_]{0,63}$' and support_vnext_shadow.closed_object(p->'expected_answer_schema',array['type','minimum','maximum','enum']) and p->'expected_answer_schema'->>'type'='integer' and (not(p->'expected_answer_schema'?'minimum') or jsonb_typeof(p->'expected_answer_schema'->'minimum')='number') and (not(p->'expected_answer_schema'?'maximum') or jsonb_typeof(p->'expected_answer_schema'->'maximum')='number') and (not(p->'expected_answer_schema'?'enum') or (jsonb_typeof(p->'expected_answer_schema'->'enum')='array' and not exists(select 1 from jsonb_array_elements(p->'expected_answer_schema'->'enum') e where jsonb_typeof(e)<>'number' or e#>>'{}' !~ '^-?[0-9]+$'))) $$;
create or replace function support_vnext_shadow.valid_plan_field_values(p jsonb) returns boolean language sql immutable as $$
 select jsonb_typeof(p)='object' and not exists(select 1 from jsonb_each(p) x where x.key !~ '^[a-z][a-z0-9_]{0,63}$' or x.key in ('subject','category','category_code','sector','setor','severity','gravidade','priority','external_route') or not (support_vnext_shadow.valid_scalar_value(x.value) or (jsonb_typeof(x.value)='array' and not exists(select 1 from jsonb_array_elements(x.value) a where jsonb_typeof(a)<>'string' or not support_vnext_shadow.is_uuid_text(a#>>'{}')))) ) $$;

create or replace function support_vnext_shadow.valid_state_patch_operation(p jsonb) returns boolean language sql immutable as $$
 select jsonb_typeof(p)='object' and case p->>'op'
 when 'CREATE_SESSION' then support_vnext_shadow.closed_object(p,array['op','session_id','release_id']) and support_vnext_shadow.is_uuid_text(p->>'session_id') and support_vnext_shadow.is_uuid_text(p->>'release_id')
 when 'CREATE_TOPIC' then support_vnext_shadow.closed_object(p,array['op','topic_id','intent_code','service_code']) and support_vnext_shadow.is_uuid_text(p->>'topic_id') and p->>'intent_code' ~ '^[A-Z][A-Z0-9_]{0,63}$' and (not(p?'service_code') or p->>'service_code' ~ '^[A-Z][A-Z0-9_]{0,63}$')
 when 'SET_TOPIC_STATUS' then support_vnext_shadow.closed_object(p,array['op','topic_id','status']) and support_vnext_shadow.is_uuid_text(p->>'topic_id') and p->>'status' in ('ACTIVE','WAITING_INPUT','WAITING_DOCUMENT','WAITING_CONFIRMATION','WAITING_HUMAN','READY_FOR_REVIEW','SCHEDULE_REQUIRED','COMPLETED','BLOCKED','A_CONFIRMAR','CANCELLED')
 when 'SET_PENDING_QUESTION' then support_vnext_shadow.closed_object(p,array['op','topic_id','question_code']) and support_vnext_shadow.is_uuid_text(p->>'topic_id') and p->>'question_code' ~ '^[A-Z][A-Z0-9_]{0,63}$'
 when 'CLEAR_PENDING_QUESTION' then support_vnext_shadow.closed_object(p,array['op','topic_id']) and support_vnext_shadow.is_uuid_text(p->>'topic_id')
 when 'MERGE_COLLECTED_DATA' then support_vnext_shadow.closed_object(p,array['op','topic_id','allowed_fields']) and support_vnext_shadow.is_uuid_text(p->>'topic_id') and support_vnext_shadow.valid_plan_field_values(p->'allowed_fields')
 when 'SET_AUTOMATION_MODE' then support_vnext_shadow.closed_object(p,array['op','mode']) and p->>'mode' in ('BOT_ACTIVE','HUMAN_ACTIVE')
 when 'SCHEDULE_INACTIVITY' then support_vnext_shadow.closed_object(p,array['op','session_id']) and support_vnext_shadow.is_uuid_text(p->>'session_id')
 when 'CANCEL_INACTIVITY' then support_vnext_shadow.closed_object(p,array['op','session_id']) and support_vnext_shadow.is_uuid_text(p->>'session_id')
 when 'CLOSE_SESSION' then support_vnext_shadow.closed_object(p,array['op','session_id','reason']) and support_vnext_shadow.is_uuid_text(p->>'session_id') and p->>'reason' ~ '^[A-Z][A-Z0-9_]{0,63}$'
 else false end $$;
create or replace function support_vnext_shadow.valid_state_patch(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['expected_state_version','operations']) and jsonb_typeof(p->'expected_state_version')='number' and p->>'expected_state_version' ~ '^[0-9]+$' and jsonb_typeof(p->'operations')='array' and not exists(select 1 from jsonb_array_elements(p->'operations') x where not support_vnext_shadow.valid_state_patch_operation(x)) $$;

create or replace function support_vnext_shadow.valid_response_plan(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['mode','template_id','template_variables','allowed_fact_refs','asset_ids','question','max_questions']) and p->>'mode' in ('DETERMINISTIC','FIELD_TEMPLATE','GEMINI') and (not(p?'template_id') or support_vnext_shadow.is_uuid_text(p->>'template_id')) and support_vnext_shadow.valid_template_variables(coalesce(p->'template_variables','{}'::jsonb)) and support_vnext_shadow.valid_fact_refs(coalesce(p->'allowed_fact_refs','[]'::jsonb)) and support_vnext_shadow.json_uuid_array(coalesce(p->'asset_ids','[]'::jsonb)) and (not(p?'question') or support_vnext_shadow.valid_question_schema(p->'question')) and coalesce(p->>'max_questions','0') in ('0','1') $$;
create or replace function support_vnext_shadow.valid_request_plan(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['mode','request_policy_id','subject_template_id','proposal_field_values','document_ids','confirmation_required']) and p->>'mode' in ('NONE','PROPOSE') and case when p->>'mode'='NONE' then not(p?'request_policy_id') and not(p?'subject_template_id') and not(p?'proposal_field_values') and not(p?'document_ids') and not(p?'confirmation_required') else support_vnext_shadow.is_uuid_text(p->>'request_policy_id') and support_vnext_shadow.is_uuid_text(p->>'subject_template_id') and support_vnext_shadow.valid_plan_field_values(coalesce(p->'proposal_field_values','{}'::jsonb)) and support_vnext_shadow.json_uuid_array(coalesce(p->'document_ids','[]'::jsonb)) and p->'confirmation_required'='true'::jsonb end $$;
create or replace function support_vnext_shadow.valid_document_plan(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['mode','requirement_ids','asset_ids','human_review_required']) and p->>'mode' in ('NONE','REQUEST','ACCEPT','SEND') and support_vnext_shadow.json_uuid_array(coalesce(p->'requirement_ids','[]'::jsonb)) and support_vnext_shadow.json_uuid_array(coalesce(p->'asset_ids','[]'::jsonb)) and jsonb_typeof(coalesce(p->'human_review_required','false'::jsonb))='boolean' $$;
create or replace function support_vnext_shadow.valid_handoff_plan(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['mode','handoff_policy_id','reason_code','queue_code','pause_bot']) and p->>'mode' in ('NONE','PROPOSE','ACTIVATE') and case when p->>'mode'='NONE' then not(p?'handoff_policy_id') and not(p?'reason_code') and not(p?'queue_code') and not(p?'pause_bot') else support_vnext_shadow.is_uuid_text(p->>'handoff_policy_id') and p->>'reason_code' ~ '^[A-Z][A-Z0-9_]{0,63}$' and (not(p?'queue_code') or jsonb_typeof(p->'queue_code') in ('string','null')) and jsonb_typeof(p->'pause_bot')='boolean' end $$;
create or replace function support_vnext_shadow.valid_validation_requirements(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['session_must_be_active','topic_id','expected_topic_version','human_must_be_inactive','confirmation_nonce_required','required_document_ids','provider_delivery_required','idempotency_key']) and (not(p?'session_must_be_active') or jsonb_typeof(p->'session_must_be_active')='boolean') and (not(p?'human_must_be_inactive') or jsonb_typeof(p->'human_must_be_inactive')='boolean') and (not(p?'confirmation_nonce_required') or jsonb_typeof(p->'confirmation_nonce_required')='boolean') and (not(p?'provider_delivery_required') or jsonb_typeof(p->'provider_delivery_required')='boolean') and support_vnext_shadow.json_uuid_array(coalesce(p->'required_document_ids','[]'::jsonb)) and (not(p?'topic_id') or support_vnext_shadow.is_uuid_text(p->>'topic_id')) and (not(p?'expected_topic_version') or (jsonb_typeof(p->'expected_topic_version')='number' and p->>'expected_topic_version' ~ '^[0-9]+$')) and (not(p?'idempotency_key') or p->>'idempotency_key' ~ '^[A-Za-z0-9._:-]{1,128}$') $$;

create or replace function support_vnext_shadow.valid_decision_plan(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['schema_version','decision_id','correlation_id','release_id','state_version','outcome','actions','response_plan','state_patch','request_plan','document_plan','handoff_plan','reason_codes','validation_requirements','a_confirmar_restrictions','expires_at']) and p->>'schema_version'='1.0' and (not(p?'release_id') or support_vnext_shadow.is_uuid_text(p->>'release_id')) and (not(p?'decision_id') or support_vnext_shadow.is_uuid_text(p->>'decision_id')) and (not(p?'correlation_id') or support_vnext_shadow.is_uuid_text(p->>'correlation_id')) and (not(p?'state_version') or (jsonb_typeof(p->'state_version')='number' and p->>'state_version' ~ '^[0-9]+$')) and p->>'outcome' in ('PERMITTED','BLOCKED','A_CONFIRMAR') and support_vnext_shadow.json_array_of_strings(p->'actions') and not exists(select 1 from jsonb_array_elements_text(p->'actions') a where a not in ('RESPONDER','FAZER_PERGUNTA','ENVIAR_DOCUMENTO','SOLICITAR_CONFIRMACAO','CRIAR_SOLICITACAO','TRANSFERIR_HUMANO','AGUARDAR_DOCUMENTO','ENCERRAR','NAO_RESPONDER_SEM_CONFIRMACAO')) and support_vnext_shadow.json_array_of_strings(p->'reason_codes') and not exists(select 1 from jsonb_array_elements_text(p->'reason_codes') x where x !~ '^[A-Z][A-Z0-9_]{0,63}$') and support_vnext_shadow.valid_state_patch(p->'state_patch') and support_vnext_shadow.valid_validation_requirements(p->'validation_requirements') and (not(p?'expires_at') or support_vnext_shadow.is_timestamptz_text(p->>'expires_at')) and (p->'response_plan'='null'::jsonb or support_vnext_shadow.valid_response_plan(p->'response_plan')) and (p->'request_plan'='null'::jsonb or support_vnext_shadow.valid_request_plan(p->'request_plan')) and (p->'document_plan'='null'::jsonb or support_vnext_shadow.valid_document_plan(p->'document_plan')) and (p->'handoff_plan'='null'::jsonb or support_vnext_shadow.valid_handoff_plan(p->'handoff_plan')) and (not(p?'a_confirmar_restrictions') or (support_vnext_shadow.json_array_of_strings(p->'a_confirmar_restrictions') and not exists(select 1 from jsonb_array_elements_text(p->'a_confirmar_restrictions') x where x not in ('NO_PRICE','NO_DEADLINE','NO_SLA','NO_REQUIRED_DOCUMENT','NO_ADMINISTRATIVE_PROPOSAL','NO_LEGACY_FALLBACK')))) and case when p->>'outcome'='A_CONFIRMAR' then p->'response_plan'='null'::jsonb and p->'request_plan'='null'::jsonb and p->'document_plan'='null'::jsonb and p->'handoff_plan'='null'::jsonb and not ((p->'actions') ?| array['CRIAR_SOLICITACAO','SOLICITAR_CONFIRMACAO','ENVIAR_DOCUMENTO','TRANSFERIR_HUMANO']) and not support_vnext_shadow.json_has_forbidden_key(p) else true end $$;

create or replace function support_vnext_shadow.valid_decision_rule_when(p jsonb) returns boolean language sql immutable as $$
 select support_vnext_shadow.closed_object(p,array['intent_code','service_code','location_type','message_role','requires_pending_confirmation']) and (not(p?'intent_code') or p->>'intent_code' ~ '^[A-Z][A-Z0-9_]{0,63}$') and (not(p?'service_code') or p->>'service_code' ~ '^[A-Z][A-Z0-9_]{0,63}$') and (not(p?'location_type') or p->>'location_type' in ('QUADRA_GERAL','JAZIGO','OSSUARIO')) and (not(p?'message_role') or p->>'message_role' in ('UNKNOWN','CONFIRMATION_AFFIRMATIVE','CONFIRMATION_NEGATIVE','COMMAND','DOCUMENT_SUBMISSION','CONTINUATION','ANSWER_TO_PENDING_QUESTION','NEW_TOPIC','TOPIC_CHANGE')) and (not(p?'requires_pending_confirmation') or jsonb_typeof(p->'requires_pending_confirmation')='boolean') $$;
create or replace function support_vnext_shadow.validate_decision_rule_shape() returns trigger language plpgsql security invoker set search_path=pg_catalog,support_vnext_shadow as $$
begin
 if not support_vnext_shadow.valid_decision_rule_when(new.when_expression) or not support_vnext_shadow.valid_decision_plan(new.then_plan) then raise exception 'decision rule uses invalid closed schema' using errcode='22023'; end if;
 if new.then_plan ? 'release_id' and (new.then_plan->>'release_id')::uuid <> new.release_id then raise exception 'decision rule plan release mismatch' using errcode='22023'; end if;
 return new;
end $$;

create or replace function support_vnext_shadow.get_runtime_decision_rules(p_release_id uuid,p_intent_code text,p_service_code text,p_location_type text) returns jsonb language sql security definer set search_path=support_vnext_shadow,pg_catalog as $$
 select coalesce(jsonb_agg(to_jsonb(x) order by x.priority desc,x.rule_code,x.decision_rule_id),'[]'::jsonb) from (select r.* from support_vnext_shadow.decision_rule r left join support_vnext_shadow.knowledge_intent i on i.intent_id=r.scope_intent_id left join support_vnext_shadow.knowledge_service s on s.service_id=r.scope_service_id where r.release_id=p_release_id and r.enabled and r.record_status='PUBLISHED' and support_vnext_shadow.release_is_runtime_usable(p_release_id,now()) and (r.scope_intent_id is null or i.intent_code=p_intent_code) and (r.scope_service_id is null or s.service_code=p_service_code) and (r.scope_location_type is null or r.scope_location_type=p_location_type)) x $$;

commit;
