/**
 * Generates the static data module consumed by server/edge deployments.
 *
 * The canonical JSON files remain the source of truth.  Deno's edge bundle does
 * not include files read dynamically with `Deno.readTextFileSync`, so this small
 * deterministic generator turns them into TypeScript imports at build time.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assets = [
  ["lexiconV1", "runtime/interpreter/lexicon.v1.json"],
  ["interpretationSchema", "runtime/interpretation.schema.json"],
  ["topicsDoc", "topics.v1.json"],
  ["factsDoc", "facts.v1.json"],
  ["goalsDoc", "goals.v1.json"],
  ["relationsDoc", "relations.v1.json"],
  ["questionsDoc", "questions.v1.json"],
  ["eventsDoc", "conversation-events.v1.json"],
  ["stateSchema", "state.schema.json"],
];

const body = await Promise.all(assets.map(async ([name, relative]) => {
  const json = JSON.parse(await readFile(join(root, relative), "utf8"));
  return `export const ${name} = ${JSON.stringify(json)};`;
}));

const output = [
  "// Generated by tools/generate_runtime_assets.mjs. Do not edit by hand.",
  "// Canonical sources: *.v1.json and state.schema.json in santana-conversation-domain/.",
  "",
  ...body,
  "",
].join("\n");

await writeFile(join(root, "runtime/generated_assets.ts"), output);
