/** Embed exact approved source bytes; never reconstruct monetary values. */
import process from "node:process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const domain = join(dirname(fileURLToPath(import.meta.url)), "..");
const authority = await readFile(join(domain, "../santana-authority/catalogo/exumacao.v1.json"), "utf8");
const files = ["facts.v1.json", "goals.v1.json", "questions.v1.json", "relations.v1.json", "topics.v1.json"];
const sources = Object.fromEntries(
  await Promise.all(files.map(async (name) => [
    name,
    await readFile(join(domain, name), "utf8"),
  ])),
);
const output = [
  "// deno-fmt-ignore-file",
  "// Generated by tools/generate_authority_assets.mjs. Do not edit by hand.",
  "// Exact UTF-8 source bytes preserve the official authority release hash.",
  `export const authoritySource = ${JSON.stringify(authority)};`,
  `export const authorityDomainSources: Readonly<Record<string, string>> = ${JSON.stringify(sources)};`,
  "",
].join("\n");
const target = join(domain, "runtime/generated_authority_assets.ts");
if (process.argv.includes("--check")) {
  const actual = await readFile(target, "utf8").catch(() => null);
  if (actual !== output) throw new Error("Authority assets are stale: run generate_authority_assets.mjs");
} else {
  await writeFile(target, output);
}
